server:
  port: 8761
  
spring:
  application:
     name: eureka
     
eureka:
  server:
    enableSelfPreservation: false
  client:
    registerWithEureka: false
    fetchRegistry: false
  instance:
    hostname: localhost
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/