server:
  port: 8080
  
spring:
  application:
     name: zuul
     
zuul:
  routes:
    users:
      path: /users/**
      serviceId: users
    cells:
      path: /cells/**
      serviceId: cells
    games:
      games: /games/**
      serviceId: games

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000
        